config/routes.rb
FeedbackGem::Engine.routes.draw do
	resources :feedbacks
end

app/models/feedback_gem/application_record.rb
module FeedbackGem
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/feedback_gem/feedback.rb
module FeedbackGem
  class Feedback < ApplicationRecord
  	validates :name,:email,:subject,:description,presence: true
  	def self.search(searchname)
			where('name LIKE ?',"%#{searchname}%")
		end
  end
end

app/controllers/feedback_gem/application_controller.rb
module FeedbackGem
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/controllers/feedback_gem/feedbacks_controller.rb
require_dependency "feedback_gem/application_controller"

module FeedbackGem
  class FeedbacksController < ApplicationController
  	def index
  		@feedbacks = Feedback.order('created_at DESC')
      @feedbacks = @feedbacks.search(params[:search]) if params[:search].present?
  	end
  	def new
  		@feedback = Feedback.new
  	end
  	def show
  		feedback
  	end
  	def create
  		@feedback = Feedback.new(feedback_params)
  		if@feedback.save
        flash[:success] = "Feedback successfully created"
  			redirect_to feedbacks_path
  		else
        flash[:error] = "Feeback is not created"
  			redirect_to feedbacks_path
  		end
  	end
  	def edit
  		feedback
  	end
  	def update
  		# binding.pry
      feedback
      if @feedback.update(feedback_params)
        flash[:success] = "Feedback has been successfully updated"
  			redirect_to feedbacks_path
  		else
        flash[:error] = "Feedback not updated"
  			redirect_to feedbacks_path
  		end
  	end
  	def destroy
  		feedback
  		@feedback.destroy
      flash[:success] = "Feedback successfully destroyed"
  		redirect_to feedbacks_path
  	end
  	private
  	def feedback_params
  		params.require(:feedback).permit(:name,:email,:subject,:description)
  	end
  	def feedback
  		@feedback = Feedback.find_by(id:params[:id])
  	end
  end
end

app/helpers/feedback_gem/application_helper.rb
module FeedbackGem
  module ApplicationHelper
  end
end

app/helpers/feedback_gem/feedback_helper.rb
module FeedbackGem
  module FeedbackHelper
  	def flash_class(level)
  		case level 
  			when 'notice' then "alert alert-info"
  			when 'success' then "alert alert-success"
  			when 'error' then "alert alert-danger"
  			when 'alert' then "alert alert-error"
  		end
  	end
  end
end

app/views/feedback_gem/feedbacks/_footer.html.erb
<div class="footer">
	<p>All rights are reserved&copy;2019</p>
</div>

app/views/feedback_gem/feedbacks/_form.html.erb
<div class="row formfields">
	<div class='col col-md-2'>
		<%=f.label :name %>
	</div>
	<div class='offset-1 col col-md-9'>
		<%=f.text_field :name,:class=>"input"%>
	</div>
</div>
<div class='row formfields'>
	<div class='col col-md-2'>
		<%=f.label :email %>
	</div>
	<div class='offset-1 col col-md-9'>
		<%=f.text_field :email,:class=>"input"%>
	</div>
</div>
<div class='row formfields'>
	<div class='col col-md-2'>
		<%=f.label :subject %>
	</div>
	<div class='offset-1 col col-md-9'>
		<%=f.text_field :subject,:class=>"input"%>
	</div>
</div>
<div class='row formfields'>
	<div class='col col-md-2'>
		<%=f.label :description %>
	</div>
	<div class='offset-1 col col-md-9'>
		<%=f.text_area :description,:class=>"input"%>
	</div>
</div>

app/views/feedback_gem/feedbacks/_header.html.erb
<div class="container-fluid  header">
	<nav class="navbar navbar-expand-lg navbar-light header">
		<%=link_to feedbacks_path do %>
		  <span class="fa fa-home"></span>
		<%end%>
		<div class="collapse navbar-collapse" id="navbarNavDropdown">
	    <ul class="navbar-nav">
	      <li class="nav-item">
	        <a class="nav-link" href="#">Feedbacks</a>
	      </li>
	    </ul>
	  </div>
	</nav>
</div>

 

app/views/feedback_gem/feedbacks/edit.html.erb
<div class="container">
	<% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %>">
      <%= value %>
    </div>
	<% end %>
	<div class="new">
		<%= form_with(model: @feedback, local: true) do |f| %>
			<div class="row formfields">
				<div class='col col-md-2'>
					<%=f.label :name %>
				</div>
				<div class='offset-1 col col-md-9'>
					<%=f.text_field :name,:class=>"input",required: true %>
				</div>
			</div>
			<div class='row formfields'>
				<div class='col col-md-2'>
					<%=f.label :email %>
				</div>
				<div class='offset-1 col col-md-9'>
					<%=f.text_field :email,:class=>"input",required: true,type: "email" %>
				</div>
			</div>
			<div class='row formfields'>
				<div class='col col-md-2'>
					<%=f.label :subject %>
				</div>
				<div class='offset-1 col col-md-9'>
					<%=f.text_field :subject,:class=>"input",required: true %>
				</div>
			</div>
			<div class='row formfields'>
				<div class='col col-md-2'>
					<%=f.label :description %>
				</div>
				<div class='offset-1 col col-md-9'>
					<%=f.text_field :description,:class=>"input",required: true %>
				</div>
			</div>
			<div class="row formfields">
				<div class="offset-8 col-6 col-md-4">
					<%=link_to 'Back', feedbacks_path,:class=>'btn btn-secondary' %>
					<%=f.submit 'Update' ,:class=>'btn btn-success'%>
				</div>
			</div>
		<%end %>
	</div>
</div>

app/views/feedback_gem/feedbacks/index.html.erb
<div class="container">
	<% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %>">
      <%= value %>
    </div>
	<% end %>
	<nav class="navbar navbar-light bg-light">
		<%=link_to '#', "data-toggle"=>"modal", "data-target" => "#new",:class=>'btn btn-warning navbar-brand ml-auto' do %>
			<i>Create new feedback</i>
		<%end%>
	</nav>
	<div class="modal fade" id="new" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h5 class="modal-title" id="exampleModalLabel">Create Feedback</h5>
	        <button type="button" class="close" data-dismiss="modal" aria-label="Cancel">
	          <span aria-hidden="true">&times;</span>
	        </button>
	      </div>
	      <%= form_for :feedback,method: :post,url: feedbacks_path,:html=>{id:"new_feedback"} do |f| %>
		      <div class="modal-body">
		        <div>   
        			<%= render :partial => "form", :locals =>{:f=>f} %>
      			</div>   
		      </div>
		      <div class="modal-footer">
		        <button type="button" class="btn btn-secondary" data-dismiss="modal" id="new_feedback_cancel">Cancel</button>
		         <%=f.submit 'Create' ,:class=>'btn btn-success'%>
		      </div>
		    <%end %>
	    </div>
	  </div>
	</div>
	<div class="row">
		<div class=" table-responsive feedbacklist">
			<table class="table table-bordered table-hover" id="feedbacks_table">
				<thead class="thead-light">
					<tr>
						<th scope="col">sl.no</th>
						<th scope="col">Name</th>
						<th scope="col">Email</th>
						<th scope="col">Subject</th>
						<th scope="col">Description</th>
						<th scope="col" style="width:20%">Actions</th>
					</tr>
				</thead>
				<tbody>
					<% @feedbacks.each do |feedback| %> 
						<tr>
							<td class="feedback-list">
								<%= feedback.id %>
							</td>
							<td>
								<strong><%= feedback.name %></strong>
							</td>
							<td>
								<%= feedback.email %>
							</td>
							<td>
								<%= feedback.subject %> 
							</td>
							<td>
								<%= feedback.description %>
							</td>
							<td>
								<%= link_to '#', "data-toggle"=>"modal", "data-target" => "#show-#{feedback.id}",:class=>'btn btn-info btns' do %>
									<i class="fa fa-eye"></i>
								<% end %>
								<%= link_to '#', "data-toggle"=>"modal", "data-target" => "#edit-#{feedback.id}",:class=>'btn btn-secondary btns' do %>
									<i class="fa fa-pencil"></i>
								<% end %>
								<%= link_to '#', "data-toggle"=>"modal", "data-target" => "#delete-#{feedback.id}",:class=>'btn btn-danger btn' do %>
									<i class="fa fa-trash"></i>
								<% end %>
								<div class="modal fade" id="delete-<%= feedback.id%>" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
								 <div class="modal-dialog modal-dialog-scrollable" role="document">
								    <div class="modal-content">
								      <div class="modal-header">
								        <h5 class="modal-title" id="exampleModalScrollableTitle">Delete</h5>
								        <button type="button" class="close" data-dismiss="modal" aria-label="Cancel">
								          <span aria-hidden="true">&times;</span>
								        </button>
								      </div>
								      <div class="modal-body">
								        Do you want to delete the feedback?
								      </div>
								      <div class="modal-footer">
								        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
								        <%= link_to 'Yes', feedback_path(feedback), method: :delete, :class => 'btn btn-danger'%>
								      </div>
								    </div>
								  </div>
								</div>
								<div class="modal fade" id="show-<%= feedback.id%>" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
								 <div class="modal-dialog modal-dialog-scrollable" role="document">
								    <div class="modal-content">
								      <div class="modal-header">
								        <h5 class="modal-title" id="exampleModalScrollableTitle">Feedback from <%= feedback.name%></h5>
								        <button type="button" class="close" data-dismiss="modal" aria-label="Cancel">
								          <span aria-hidden="true">&times;</span>
								        </button>
								      </div>
								      <div class="modal-body">
									     	<div class="row">
										     	<div class="col-md-4">
										        <strong>Name:</strong>
										      </div>
										      <div class="col-md-8">
										      	<%= feedback.name %>
										      </div> 
										      <div class="col-md-4">
									        	<strong>email:</strong>
									        </div>
									        <div class="col-md-8">
									        	<%= feedback.email %>
									       	</div>
									       	<div class="col-md-4">
									        	<strong>subject:</strong>
									        </div>
									        <div class="col-md-8">
									        	<%= feedback.subject %>
									      	</div>
									      	<div class="col-md-4">
									        <strong>feedback:</strong>
									        </div>
									        <div class="col-md-8">
									        	<%= feedback.description %>
									        </div>
									      </div>
								      </div>
								      <div class="modal-footer">
								        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
								      </div>
								    </div>
								  </div>
								</div>
								<div class="modal fade edit_feedback_form" id="edit-<%= feedback.id%>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
								  <div class="modal-dialog" role="document">
								    <div class="modal-content">
								      <div class="modal-header">
								        <h5 class="modal-title" id="exampleModalLabel">Edit Feedback</h5>
								        <button type="button" class="close" data-dismiss="modal" aria-label="Cancel">
								          <span aria-hidden="true">&times;</span>
								        </button>
								      </div>
								      <%= form_for feedback,url: feedback_path(feedback),method: :put do |f| %>
									      <div class="modal-body">
									        <div>   
	                    			<%= render :partial => "form", :locals =>{:f=>f} %>
	                  			</div>   
									      </div>
									      <div class="modal-footer">
									        <button type="button" class="btn btn-secondary" data-dismiss="modal" id="edit_feedback_cancel">Cancel</button>
									         <%=f.submit 'Update' ,:class=>'btn btn-success'%>
									      </div>
									    <%end %>
								    </div>
								  </div>
								</div>
							</td>
						</tr>
					<% end %> 
				</tbody>
			</table>
		</div>
	</div>
</div>
  

app/views/feedback_gem/feedbacks/new.html.erb
<div class="container">
 
	  <nav class="navbar navbar-light bg-light">
			<%=link_to '#', "data-toggle"=>"modal", "data-target" => "#new",:class=>'btn btn-warning navbar-brand ml-auto' do %>
				<i>Create new feedback</i>
			<%end%>
		</nav>
		<div class="modal fade" id="new" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
		  <div class="modal-dialog" role="document">
		    <div class="modal-content">
		      <div class="modal-header">
		        <h5 class="modal-title" id="exampleModalLabel">Create Feedback</h5>
		        <button type="button" class="close" data-dismiss="modal" aria-label="Cancel">
		          <span aria-hidden="true">&times;</span>
		        </button>
		      </div>
		      <%= form_for :feedback,method: :post,url: feedbacks_path,:html=>{id:"new_feedback"} do |f| %>
			      <div class="modal-body">
			        <div>   
	        			<%= render :partial => "form", :locals =>{:f=>f} %>
	      			</div>   
			      </div>
			      <div class="modal-footer">
			        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
			         <%=f.submit 'Create' ,:class=>'btn btn-success'%>
			      </div>
			    <%end %>
		    </div>
		  </div>
		</div>
	 

	<!-- Columns start at 50% wide on mobile and bump up to 33.3% wide on desktop -->
	<div class="row">
		 
			<table class="table table-bordered table-hover" id="new-table">
				<thead>
		      <tr>
		          
		        <th>Heading</th>
		         <th>Heading</th>
		        <th>Heading</th>
		         <th>Heading</th>
		        <th>Heading</th>
		         <th>Heading</th>
		        <th>Heading</th> 
		        <th>Heading</th>
		        <th>Heading</th>
		      </tr>
		    </thead>
		    <tbody>
		      <tr>
		        
		        <td>Cell</td>
		        <td>Cell</td>
		        <td>Cell</td>
		        <td>Cell</td>
		        <td>Cell</td>
		        <td>Use .table-responsive{-sm|-md|-lg|-xl} classes as needed to create responsive tables up to a particular breakpoint. From that breakpoint and up, the table will behave normally and not scroll horizontally. Use .table-responsive{-sm|-md|-lg|-xl} classes as needed to create responsive tables up to a particular breakpoint. From that breakpoint and up, the table will behave normally and not scroll horizontally.</td>
		        <td>Cell</td>
		        <td>Cell</td>
		        <td>Cell</td>
		      </tr>
		      <tr>
		      
		        <td>Cell</td>
		        <td>Cell</td>
		        <td>Cell</td>
		        <td>Cell</td>
		        <td>Cell</td>
		        <td>Cell</td>
		        <td>Cell</td>
		        <td>Cell</td>
		        <td>Cell</td>
		      </tr>
		      
		    </tbody>
		  </table>
	 
	</div>

	 
	 
</div>

app/views/feedback_gem/feedbacks/show.html.erb
<div class="container">
	<% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %>">
      <%= value %>
    </div>
	<% end %>
	<div class='card card-style'>
		<div class='card-header'>
			<h4>feedback from <%= @feedback.name%></h4>
		</div>
		<div class='card-body'>
			<p class='card-text'><strong>Name:</strong><%= @feedback.name %></p>
			<p class='card-text'><strong>Email:</strong><%= @feedback.email %></p>
			<p class='card-text'><strong>Subject:</strong><%= @feedback.subject %></p>
			<p class='card-text'><strong>Feedback:</strong><%= @feedback.description %></p>
		</div>
		<div class='card-footer'>
			<div class='footer-style'>
				<%=link_to 'Back', feedbacks_path,:class=>'btn btn-secondary' %>
				<%=link_to 'edit', edit_feedback_path,:class=>'btn btn-success' %>
			</div>
		</div>
	</div>
</div>

app/views/layouts/feedback_gem/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Feedback gem</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    "feedback_gem/application", media: "all" %>
  <%= javascript_include_tag "feedback_gem/application" %>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.15.1/jquery.validate.min.js" %>
  <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.15.1/additional-methods.min.js" %>
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
  <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
</head>
<body>
<%= render "feedback_gem/feedbacks/header" %>
<%= yield %>
<%= render "feedback_gem/feedbacks/footer" %>
</body>
</html>